version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - nadnoslen
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.24.0
    - 7.25.0
    - 7.26.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: "@aws-amplify/auth"
    versions:
    - 3.4.17
    - 3.4.18
    - 3.4.19
    - 3.4.20
    - 3.4.21
    - 3.4.22
    - 3.4.23
    - 3.4.24
    - 3.4.25
    - 3.4.26
    - 3.4.27
    - 3.4.28
    - 3.4.29
  - dependency-name: "@aws-amplify/core"
    versions:
    - 3.8.10
    - 3.8.11
    - 3.8.12
    - 3.8.13
    - 3.8.14
    - 3.8.15
    - 3.8.16
    - 3.8.17
    - 3.8.18
    - 3.8.19
    - 3.8.20
    - 3.8.21
    - 3.8.9
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-concurrency
    versions:
    - 1.3.0
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
